-- ============================================================
-- Tabel Bank Soal Edukasi Sakkah
-- Database: sakah_quiz_db
-- Engine: PostgreSQL
-- Target: @vercel/postgres / Vercel Postgres
-- ============================================================

CREATE TABLE IF NOT EXISTS quiz_modul (
  id            BIGSERIAL PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,
  title         TEXT NOT NULL,
  description   TEXT,
  image_folder  TEXT,
  sort_order    INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO quiz_modul (id, slug, title, description, image_folder, sort_order, is_active) VALUES
(1, 'murabahah', 'Murabahah', 'Jual beli dengan harga beruntung yang disepakati dan diketahui kedua pihak.', 'murabahah', 1, TRUE),
(2, 'salam', 'Salam', 'Pembelian barang di masa depan dengan pembayaran di muka.', 'salam', 2, TRUE),
(3, 'istishna', 'Istishna', 'Pesanan pembuatan barang dengan spesifikasi dan harga yang disepakati.', 'istishna', 3, TRUE),
(4, 'mudharabah', 'Mudharabah', 'Kerja sama modal dan keahlian dengan pembagian hasil.', 'mudharabah', 4, TRUE),
(5, 'musyarakah', 'Musyarakah', 'Kerja sama bersama dengan kontribusi dari beberapa pihak.', 'musyarakah', 5, TRUE),
(6, 'ijarah', 'Ijarah', 'Sewa menyewa aset untuk periode tertentu.', 'ijarah', 6, TRUE),
(7, 'ijarah-muntahiya-bi-al-tamlik', 'Ijarah Muntahiya Bi al Tamlik', 'Sewa yang pada akhirnya dapat mengarah pada kepemilikan.', 'ijarah-muntahiya-bi-al-tamlik', 7, TRUE),
(8, 'wakalah', 'Wakalah', 'Pemberian wewenang kepada wakil untuk melakukan tindakan tertentu.', 'wakalah', 8, TRUE),
(9, 'qardh-al-hasan', 'Qardh al Hasan', 'Pemberian pinjaman yang bersifat membantu, tanpa keuntungan tambahan.', 'qardh-al-hasan', 9, TRUE),
(10, 'wadiah', 'Wadiah', 'Pencatutan uang atau aset dengan fokus keamanan.', 'wadiah', 10, TRUE),
(11, 'kafalah', 'Kafalah', 'Menjamin pemenuhan kewajiban pihak lain.', 'kafalah', 11, TRUE),
(12, 'rahn', 'Rahn', 'Jaminan berupa hak milik tertentu untuk mengamankan kewajiban.', 'rahn', 12, TRUE);

CREATE TABLE IF NOT EXISTS quiz_soal (
  id            BIGSERIAL PRIMARY KEY,
  modul_id      BIGINT NOT NULL REFERENCES quiz_modul(id) ON DELETE CASCADE,
  question      TEXT NOT NULL,
  option_a      TEXT NOT NULL,
  option_b      TEXT NOT NULL,
  option_c      TEXT NOT NULL,
  option_d      TEXT NOT NULL,
  answer_index  SMALLINT NOT NULL CHECK (answer_index BETWEEN 1 AND 4),
  explanation   TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_pilihan (
  id            BIGSERIAL PRIMARY KEY,
  soal_id       BIGINT NOT NULL REFERENCES quiz_soal(id) ON DELETE CASCADE,
  option_number SMALLINT NOT NULL CHECK (option_number BETWEEN 1 AND 4),
  option_text   TEXT NOT NULL,
  is_correct    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS quiz_jawaban_benar (
  id            BIGSERIAL PRIMARY KEY,
  soal_id       BIGINT NOT NULL UNIQUE REFERENCES quiz_soal(id) ON DELETE CASCADE,
  answer_index  SMALLINT NOT NULL CHECK (answer_index BETWEEN 1 AND 4)
);

INSERT INTO quiz_soal (id, modul_id, question, option_a, option_b, option_c, option_d, answer_index, explanation) VALUES
(1, 1, 'Apa ciri utama transaksi Murabahah?', 'Menjual barang dengan margin untung yang tidak diketahui pembeli', 'Menjual barang dengan harga beruntang yang disepakati dan diketahui kedua pihak', 'Menjual barang tanpa biaya apa pun', 'Menjual barang berdasarkan hasil akhir yang hanya dibagi nanti', 2, 'Murabahah mensyaratkan harga dan keuntungan yang disepakati dan diketahui.'),
(2, 1, 'Dalam Murabahah, siapa yang menentukan margin keuntungan?', 'Hanya pembeli', 'Hanya pedagang tanpa konsultasi', 'Kedua pihak secara disepakati', 'Sistem otomatis tanpa persetujuan', 3, 'Baik pembeli maupun penjual harus setuju atas keuntungan yang ditetapkan.'),
(3, 1, 'Mengapa hal yang penting dalam Murabahah adalah keterbukaan harga?', 'Agar penjual bisa menyembunyikan biaya', 'Agar pembeli bisa menilai keadilan transaksi', 'Agar harga bisa diubah kapan saja', 'Agar barang tidak perlu dilelang', 2, 'Transparansi harga membantu kepercayaan dan keadilan dalam akad.'),
(4, 1, 'Mana yang paling cocok dengan Murabahah?', 'Jual beli dengan harga final yang jelas dan diketahui', 'Jual beli dengan untung yang ditentukan sendiri pembeli', 'Sewa barang tanpa batas waktu', 'Pinjaman tanpa pikiran keadilan', 1, 'Murabahah menekankan harga dan keuntungan yang diketahui.'),
(5, 1, 'Murabahah cocok digunakan ketika...', 'Pembeli ingin tahu harga akhir dan untungnya', 'Pembeli ingin hasil yang dirahasiakan', 'Kedua pihak menghindari kesepakatan', 'Barang dijual tanpa syarat', 1, 'Kesepakatan harga menjadi poin penting Murabahah.'),
(6, 2, 'Apa karakteristik utama Salam?', 'Pembayaran dilakukan setelah barang siap sepenuhnya', 'Pembelian barang masa depan dengan pembayaran di muka', 'Penjualan barang dengan biaya tersembunyi', 'Sewa barang dalam waktu lama', 2, 'Salam adalah pembelian barang yang akan diproduksi/disediakan di masa depan, dengan pembayaran penuh di muka.'),
(7, 2, 'Pembayaran biasanya dilakukan pada Salam ketika...', 'Pengiriman barang akhir', 'Awal akad dan sebelum barang diserahkan', 'Setelah barang rusak', 'Saat produsen meminta tambahan', 2, 'Pembayaran di muka adalah bagian penting dari akad Salam.'),
(8, 2, 'Mana yang paling sesuai dengan Salam?', 'Membeli tanaman yang sudah tumbuh di ladang', 'Memesan beras yang akan dipanen nanti dengan bayar di awal', 'Menyewakan alat pertanian untuk satu musim', 'Mengambil pinjaman dengan bunga', 2, 'Salam cocok untuk pembelian sesuatu yang akan tersedia di masa depan.'),
(9, 2, 'Barang yang dibeli dalam Salam umumnya...', 'Siap kirim saat ini', 'Akan diproduksi atau tersedia nanti', 'Hanya produk bekas', 'Barang yang rusak', 2, 'Salam berfokus pada barang masa depan.'),
(10, 2, 'Salam bertujuan membantu transaksi ketika...', 'Pembeli menginginkan kepastian harga awal', 'Pembeli tidak ingin tahu apa pun', 'Penjual menolak transparansi', 'Harga selalu berubah tanpa aturan', 1, 'Kesepakatan awal membantu kepastian dalam Salam.'),
(11, 3, 'Istishna umumnya berkaitan dengan...', 'Penjualan barang jadi yang sudah ada di toko', 'Pesanan pembuatan barang dengan spesifikasi tertentu', 'Sewa peralatan tanpa kepemilikan', 'Pembagian modal tanpa aturan', 2, 'Istishna adalah akad pesanan untuk produksi atau pembuatan barang.'),
(12, 3, 'Pihak yang memesan dalam Istishna biasanya...', 'Membayar setelah barang selesai tanpa ketentuan awal', 'Menetapkan syarat dan harga pada awal akad', 'Menyerahkan semua risiko tanpa syarat', 'Menghindari spesifikasi barang', 2, 'Spesifikasi dan ketentuan awal penting dalam akad pesanan.'),
(13, 3, 'Contoh Istishna yang paling tepat adalah...', 'Membeli laptop siap jual dari gudang', 'Memesan buatan perangkat khusus sesuai kebutuhan', 'Menyewa laptop untuk cek email', 'Meminjam uang dari teman', 2, 'Istishna adalah pesanan pembuatan barang sesuai ketentuan.'),
(14, 3, 'Istishna memungkinkan...', 'Barang dibuat sesuai ketentuan yang disepakati', 'Barang dijual tanpa konsultasi sama sekali', 'Barang diberikan gratis', 'Barang diabaikan', 1, 'Istishna menekankan pembuatan sesuai permintaan.'),
(15, 3, 'Perbedaan Istishna dari penjualan biasa adalah...', 'Barang tidak perlu ada saat akad', 'Barang dibuat sesuai pesanan setelah akad', 'Barang tidak memiliki spesifikasi', 'Barang tidak bisa digunakan', 2, 'Istishna berkaitan dengan pembuatan barang yang belum ada saat akad.'),
(16, 4, 'Apa prinsip utama Mudharabah?', 'Pinjaman dengan bunga yang tetap', 'Kerja sama antara pemilik modal dan pengelola usaha dengan pembagian hasil', 'Sewa aset selama waktu tertentu', 'Menjual barang secara tunai saja', 2, 'Mudharabah menggabungkan modal dan keahlian, dengan pembagian hasil sesuai akad.'),
(17, 4, 'Dalam Mudharabah, kehilangan modal karena kesalahan umumnya ditanggung oleh...', 'Semua pihak secara sama rata', 'Pengelola jika karena kesalahan atau kelalaiannya', 'Hanya pembeli akhir', 'Pemerintah', 2, 'Tanggung jawab umumnya mengikuti peran dan perilaku pihak yang bersangkutan.'),
(18, 4, 'Siapa yang biasanya membawa modal dalam Mudharabah?', 'Pengelola usaha saja', 'Pihak yang memberikan pembiayaan', 'Penjual barang', 'Penyewa aset', 2, 'Pemilik modal memberikan pembiayaan, sementara pengelola menjalankan usaha.'),
(19, 4, 'Hasil dalam Mudharabah dibagi berdasarkan...', 'Nomor urutan nama', 'Persentase yang disepakati bersama', 'Besar fisik pengelola', 'Lokasi bank', 2, 'Pembagian hasil disesuaikan dengan kesepakatan.'),
(20, 4, 'Mana yang merupakan contoh Mudharabah?', 'Satu pihak memberi uang, pihak lain mengelola usaha, hasil dibagi', 'Satu pihak menjual barang tunai', 'Menyewa ruang kantor seharian', 'Memberikan sukarela tanpa kepastian', 1, 'Mudharabah menggabungkan pembiayaan dan pengelolaan.'),
(21, 5, 'Perbedaan Musyarakah dan Mudharabah secara umum adalah...', 'Musyarakah tidak melibatkan uang', 'Musyarakah melibatkan kontribusi dari beberapa pihak dalam modal dan/atau keahlian', 'Musyarakah hanya untuk sewa', 'Musyarakah tidak perlu akad', 2, 'Musyarakah adalah kerja sama bersama dengan kontribusi masing-masing.'),
(22, 5, 'Dalam Musyarakah, hasil biasanya dibagi berdasarkan...', 'Nomor antrian', 'Persentase kontribusi atau kesepakatan yang disepakati', 'Yang paling dulu datang', 'Besar badan pengelola', 2, 'Pembagian hasil disesuaikan dengan kesepakatan bersama.'),
(23, 5, 'Mana yang paling menggambarkan Musyarakah?', 'Satu orang memberi modal dan orang lain mengelola saja', 'Dua mitra sama-sama memberi modal dan berdiskusi dalam pengelolaan', 'Menyewa ruang kantor sebesar mungkin', 'Menjual barang dengan marjin tersembunyi', 2, 'Musyarakah menekankan kontribusi bersama.'),
(24, 5, 'Dalam Musyarakah, setiap pihak umumnya...', 'Tidak punya peran', 'Memberikan kontribusi sesuai kesepakatan', 'Hanya menonton', 'Menjual tanpa partisipasi', 2, 'Musyarakah melibatkan partisipasi beberapa pihak.'),
(25, 5, 'Konsep Musyarakah sangat cocok ketika...', 'Hanya satu orang yang ingin mengambil risiko', 'Beberapa pihak ingin berinvestasi bersama', 'Barang dijual tanpa pembicaraan', 'Sewa dilakukan secara diam-diam', 2, 'Musyarakah memungkinkan kerja sama multipihak.'),
(26, 6, 'Ijarah secara sederhana berarti...', 'Menjual barang dengan harga tinggi', 'Menyewakan aset untuk penggunaan dalam waktu tertentu', 'Meminjamkan uang dengan bunga', 'Menyumbang barang tanpa syarat', 2, 'Ijarah adalah akad sewa menyewa.'),
(27, 6, 'Siapa yang memiliki hak pakai dalam Ijarah?', 'Penyewa selama periode sewa', 'Penjual di seluruh masa', 'Pengelola dana', 'Penjamin kredit', 1, 'Dalam Ijarah, hak pakai diberikan kepada penyewa untuk periode yang disepakati.'),
(28, 6, 'Mana yang merupakan contoh Ijarah?', 'Membeli mobil baru secara tunai', 'Menyewa alat kantor untuk proyek tertentu', 'Menyumbang buku ke perpustakaan', 'Menanam pohon di sawah', 2, 'Penyewaan aset mengarah ke Ijarah.'),
(29, 6, 'Ijarah berbeda dari jual beli karena...', 'Aset tetap menjadi hak penyewa selama sewa', 'Aset langsung berpindah kepemilikan', 'Barang hilang begitu saja', 'Harga tidak penting', 1, 'Ijarah berfokus pada hak pakai, bukan kepemilikan penuh.'),
(30, 6, 'Yang umumnya disepakati dalam Ijarah adalah...', 'Barang tidak dipakai sama sekali', 'Jangka waktu dan ketentuan penggunaan aset', 'Modal yang tidak dikembalikan', 'Sewa tanpa batas waktu tanpa aturan', 2, 'Iariah menetapkan waktu dan cara penggunaan aset.'),
(31, 7, 'Ijarah Muntahiya Bi al Tamlik berbeda dari Ijarah biasa karena...', 'Tidak ada biaya sewa', 'Pada akhirnya bisa mengarah pada kepemilikan aset', 'Hanya berlaku untuk makanan', 'Dilakukan tanpa akad', 2, 'Bentuk ini mengakhiri periode sewa dengan kemungkinan kepemilikan.'),
(32, 7, 'Contoh konteks Ijarah Muntahiya Bi al Tamlik adalah...', 'Menyewa rumah untuk liburan singkat', 'Menyewa aset dengan opsi kepemilikan di akhir', 'Menjual sepeda kepada tetangga', 'Meminjam buku dari perpustakaan', 2, 'Struktur ini menggabungkan penggunaan sewa dan kemungkinan kepemilikan.'),
(33, 7, 'Pada tahap akhir Ijarah Muntahiya Bi al Tamlik...', 'Sewa otomatis berhenti tanpa klausul', 'Aset bisa beralih kepemilikan sesuai ketentuan yang disepakati', 'Penyewa kehilangan semua hak', 'Penjual wajib merusak aset', 2, 'Ketentuan akhir bisa mengarah pada transfer hak kepemilikan.'),
(34, 7, 'Istilah "Muntahiya Bi al Tamlik" mengarah pada...', 'Penutupan sewa tanpa akhir', 'Kemungkinan kepemilikan di akhir', 'Penyewaan tanpa aturan', 'Kerusakan aset', 2, 'Frasa ini mengaitkan sewa dengan kemungkinan kepemilikan.'),
(35, 7, 'Mengapa Ijarah Muntahiya Bi al Tamlik digunakan?', 'Agar penyewa bisa memakai aset lalu memilikiinya sesuai kesepakatan', 'Agar aset hilang', 'Agar harga tetap sembunyi', 'Agar tidak ada akhir', 1, 'Murabahkan aliran sewa-kepemilikan sesuai kesepakatan.'),
(36, 8, 'Wakalah adalah hubungan antara...', 'Peminjam dan bank saja', 'Pemberi wewenang dan wakil yang menjalankan tugas tertentu', 'Penyewa dan penyewa lanjutan', 'Penjual dan pembeli tunai', 2, 'Wakalah melibatkan pemberian wewenang kepada wakil.'),
(37, 8, 'Siapa yang bertindak atas nama pihak lain dalam Wakalah?', 'Penjamin', 'Wakil', 'Penyewa', 'Pedagang eceran', 2, 'Wakil menjalankan tugas atas wewenang yang diberikan.'),
(38, 8, 'Contoh Wakalah yang paling tepat adalah...', 'Menyewakan motor untuk satu hari', 'Memberikan wewenang orang lain untuk mengurus urusan tertentu', 'Menjual buku di jalan', 'Meminjam uang dari koperasi', 2, 'Wakalah berfokus pada pemberian mandat/wewenang.'),
(39, 8, 'Wakalah memungkinkan orang lain untuk...', 'Bertindak atas nama pemberi wewenang dalam lingkup tertentu', 'Merusak aset pemberi wewenang', 'Menjual semua barang tanpa izin', 'Mengabaikan perjanjian', 1, 'Wakil bertindak sesuai wewenang yang diberikan.'),
(40, 8, 'Batasan wewenang dalam Wakalah penting agar...', 'Wakil bisa bertindak tanpa aturan', 'Tindakan tetap sesuai yang disepakati', 'Semua keputusan hilang', 'Barang jadi milik wakil', 2, 'Batasan wewenang menjaga kejelasan peran.'),
(41, 9, 'Qardh al Hasan adalah pinjaman yang...', 'Menguntungkan pemberi pinjaman dengan bunga', 'Bersifat membantu tanpa keuntungan tambahan', 'Selalu ditjamin emas', 'Hanya untuk bisnis besar', 2, 'Qardh al Hasan menekankan bantuan, bukan keuntungan.'),
(42, 9, 'Dalam Qardh al Hasan, kelebihan yang diberikan umumnya...', 'Wajib dibagi sebagai bunga', 'Dapat bersifat sukarela atau pengembalian pokok saja', 'Tidak boleh dikembalikan', 'Dihitung otomatis tiap jam', 2, 'Inti bantuan adalah pengembalian pokok, tanpa keuntungan yang dipaksa.'),
(43, 9, 'Mana yang paling sesuai dengan Qardh al Hasan?', 'Menjual barang dengan margin 50 persen', 'Memberikan pinjaman untuk membantu kebutuhan dengan pengembalian pokok', 'Menyewakan rumah dengan persentase hasil', 'Membeli saham tanpa risiko', 2, 'Qardh al Hasan adalah bentuk pemberian pinjaman yang membantu.'),
(44, 9, 'Qardh al Hasan lebih menekankan pada...', 'Keuntungan pihak pemberi', 'Bantuan kepada pihak yang membutuhkan', 'Sewa aset', 'Pembagian modal', 2, 'Qardh al Hasan bersifat membantu.'),
(45, 9, 'Qardh al Hasan bisa berperan ketika...', 'Tujuannya meminta bantuan bukan mencari untung', 'Tujuannya menjual barang', 'Tujuannya menyewa alat', 'Tujuannya membagi hasil usaha', 1, 'Qardh al Hasan cocok untuk pinjaman bantuan.'),
(46, 10, 'Wadiah berkaitan dengan...', 'Penjualan barang secara masa depan', 'Pencatutan uang atau aset dengan penekanan pada keamanan', 'Sewa alat industri', 'Pinjaman berbunga', 2, 'Wadiah adalah bentuk penitipan dengan fokus keamanan.'),
(47, 10, 'Keamanan dalam Wadiah menekankan pada...', 'Menyembunyikan alasan', 'Menjaga kepercayaan dan perlindungan aset', 'Meningkatkan risiko', 'Mengurangi jumlah aset', 2, 'Wadiah menekankan keamanan dan kejelasan.'),
(48, 10, 'Mana yang paling menggambarkan Wadiah?', 'Menjual hasil panen sebelum panen', 'Menitipkan uang dengan perjanjian keamanan', 'Menyewa truk pengiriman', 'Memberikan bunga kepada nasabah', 2, 'Menitipkan aset dengan kesepakatan keamanan menggambarkan Wadiah.'),
(49, 10, 'Wadiah cocok untuk situasi ketika orang ingin...', 'Menyimpan aset dengan perlindungan yang jelas', 'Menjual aset secara langsung', 'Menyewa alat produksi', 'Memberikan bunga', 1, 'Wadiah berpusat pada penitipan dan keamanan.'),
(50, 10, 'Penekanan utama Wadiah adalah...', 'Keuntungan tambahan', 'Keamanan aset yang dititipkan', 'Pembagian hasil usaha', 'Sewa jangka panjang', 2, 'Wadiah berfokus pada keamanan aset.'),
(51, 11, 'Kafalah biasanya muncul dalam konteks...', 'Menjual makanan', 'Menjamin pemenuhan kewajiban pihak lain', 'Menyewa alat tulis', 'Menanam pohon', 2, 'Kafalah adalah bentuk penjaminan.'),
(52, 11, 'Dalam Kafalah, pihak yang menjamin berperan sebagai...', 'Pendaftar investasi', 'Penjamin apabila ada kewajiban yang perlu dipenuhi', 'Penjual barang', 'Pedagang eceran', 2, 'Kafalah memberikan peran penjaminan.'),
(53, 11, 'Mana yang paling sesuai dengan Kafalah?', 'Memberikan jaminan atas kewajiban seorang mitra usaha', 'Menjual sepeda bekas', 'Menyewakan laptop', 'Mengambil pinjaman berbunga', 1, 'Kafalah berhubungan dengan menjamin kewajiban.'),
(54, 11, 'Kafalah membantu ketika...', 'Ada kebutuhan jaminan atas kewajiban tertentu', 'Barang dijual tanpa penjelasan', 'Modal tidak punya mitra', 'Sewa tidak perlu perjanjian', 1, 'Kafalah berfokus pada jaminan kewajiban.'),
(55, 11, 'Perbedaan Kafalah dan Rahn terletak pada...', 'Kafalah berfokus pada menjamin pemenuhan kewajiban, Rahn memberi jaminan atas aset tertentu', 'Keduanya sama persis', 'Kafalah tidak butuh pihak lain', 'Kafalah hanya untuk makanan', 1, 'Kafalah dan Rahn punya fokus berbeda.'),
(56, 12, 'Rahn adalah...', 'Jaminan berupa hak milik tertentu untuk mengamankan kewajiban', 'Sewa tahunan', 'Barang hasil donasi', 'Jenis bunga', 1, 'Rahn adalah bentuk jaminan dengan objek tertentu.'),
(57, 12, 'Objek jaminan dalam Rahn biasanya bersifat...', 'Tidak berkaitan sama sekali', 'Milik pihak yang memberikan jaminan', 'Harta benda yang hilang', 'Hak suara saja', 2, 'Jaminan dalam Rahn umumnya berasal dari hak milik tertentu.'),
(58, 12, 'Contoh Rahn yang paling tepat adalah...', 'Menyewakan kendaraan', 'Menjamin kewajiban dengan memberikan hak atas aset tertentu', 'Menjual buku pribadi', 'Memberikan barang secara gratis', 2, 'Rahn menggunakan aset sebagai jaminan.'),
(59, 12, 'Rahn berfungsi sebagai...', 'Jaminan tambahan untuk kewajiban', 'Pembagian hasil usaha', 'Sewa alat tahunan', 'Donasi tanpa syarat', 1, 'Rahn adalah jaminan untuk mengamankan kewajiban.'),
(60, 12, 'Mana yang paling tepat menggambarkan Rahn?', 'Aset digunakan sebagai jaminan atas pinjaman atau kewajiban', 'Barang dijual tanpa harga', 'Barang disewakan tanpa syarat', 'Barang diberikan secara sukarela tanpa jaminan', 1, 'Rahn melibatkan aset sebagai jaminan.');

INSERT INTO quiz_pilihan (soal_id, option_number, option_text, is_correct) VALUES
(1, 1, 'Menjual barang dengan margin untung yang tidak diketahui pembeli', FALSE),
(1, 2, 'Menjual barang dengan harga beruntang yang disepakati dan diketahui kedua pihak', TRUE),
(1, 3, 'Menjual barang tanpa biaya apa pun', FALSE),
(1, 4, 'Menjual barang berdasarkan hasil akhir yang hanya dibagi nanti', FALSE),

(2, 1, 'Hanya pembeli', FALSE),
(2, 2, 'Hanya pedagang tanpa konsultasi', FALSE),
(2, 3, 'Kedua pihak secara disepakati', TRUE),
(2, 4, 'Sistem otomatis tanpa persetujuan', FALSE),

(3, 1, 'Agar penjual bisa menyembunyikan biaya', FALSE),
(3, 2, 'Agar pembeli bisa menilai keadilan transaksi', TRUE),
(3, 3, 'Agar harga bisa diubah kapan saja', FALSE),
(3, 4, 'Agar barang tidak perlu dilelang', FALSE),

(4, 1, 'Jual beli dengan harga final yang jelas dan diketahui', TRUE),
(4, 2, 'Jual beli dengan untung yang ditentukan sendiri pembeli', FALSE),
(4, 3, 'Sewa barang tanpa batas waktu', FALSE),
(4, 4, 'Pinjaman tanpa pikiran keadilan', FALSE),

(5, 1, 'Pembeli ingin tahu harga akhir dan untungnya', TRUE),
(5, 2, 'Pembeli ingin hasil yang dirahasiakan', FALSE),
(5, 3, 'Kedua pihak menghindari kesepakatan', FALSE),
(5, 4, 'Barang dijual tanpa syarat', FALSE),

(6, 1, 'Pembayaran dilakukan setelah barang siap sepenuhnya', FALSE),
(6, 2, 'Pembelian barang masa depan dengan pembayaran di muka', TRUE),
(6, 3, 'Penjualan barang dengan biaya tersembunyi', FALSE),
(6, 4, 'Sewa barang dalam waktu lama', FALSE),

(7, 1, 'Pengiriman barang akhir', FALSE),
(7, 2, 'Awal akad dan sebelum barang diserahkan', TRUE),
(7, 3, 'Setelah barang rusak', FALSE),
(7, 4, 'Saat produsen meminta tambahan', FALSE),

(8, 1, 'Membeli tanaman yang sudah tumbuh di ladang', FALSE),
(8, 2, 'Memesan beras yang akan dipanen nanti dengan bayar di awal', TRUE),
(8, 3, 'Menyewakan alat pertanian untuk satu musim', FALSE),
(8, 4, 'Mengambil pinjaman dengan bunga', FALSE),

(9, 1, 'Siap kirim saat ini', FALSE),
(9, 2, 'Akan diproduksi atau tersedia nanti', TRUE),
(9, 3, 'Hanya produk bekas', FALSE),
(9, 4, 'Barang yang rusak', FALSE),

(10, 1, 'Pembeli menginginkan kepastian harga awal', TRUE),
(10, 2, 'Pembeli tidak ingin tahu apa pun', FALSE),
(10, 3, 'Penjual menolak transparansi', FALSE),
(10, 4, 'Harga selalu berubah tanpa aturan', FALSE),

(11, 1, 'Penjualan barang jadi yang sudah ada di toko', FALSE),
(11, 2, 'Pesanan pembuatan barang dengan spesifikasi tertentu', TRUE),
(11, 3, 'Sewa peralatan tanpa kepemilikan', FALSE),
(11, 4, 'Pembagian modal tanpa aturan', FALSE),

(12, 1, 'Membayar setelah barang selesai tanpa ketentuan awal', FALSE),
(12, 2, 'Menetapkan syarat dan harga pada awal akad', TRUE),
(12, 3, 'Menyerahkan semua risiko tanpa syarat', FALSE),
(12, 4, 'Menghindari spesifikasi barang', FALSE),

(13, 1, 'Membeli laptop siap jual dari gudang', FALSE),
(13, 2, 'Memesan buatan perangkat khusus sesuai kebutuhan', TRUE),
(13, 3, 'Menyewa laptop untuk cek email', FALSE),
(13, 4, 'Meminjam uang dari teman', FALSE),

(14, 1, 'Barang dibuat sesuai ketentuan yang disepakati', TRUE),
(14, 2, 'Barang dijual tanpa konsultasi sama sekali', FALSE),
(14, 3, 'Barang diberikan gratis', FALSE),
(14, 4, 'Barang diabaikan', FALSE),

(15, 1, 'Barang tidak perlu ada saat akad', TRUE),
(15, 2, 'Barang dibuat sesuai pesanan setelah akad', FALSE),
(15, 3, 'Barang tidak memiliki spesifikasi', FALSE),
(15, 4, 'Barang tidak bisa digunakan', FALSE),

(16, 1, 'Pinjaman dengan bunga yang tetap', FALSE),
(16, 2, 'Kerja sama antara pemilik modal dan pengelola usaha dengan pembagian hasil', TRUE),
(16, 3, 'Sewa aset selama waktu tertentu', FALSE),
(16, 4, 'Menjual barang secara tunai saja', FALSE),

(17, 1, 'Semua pihak secara sama rata', FALSE),
(17, 2, 'Pengelola jika karena kesalahan atau kelalaiannya', TRUE),
(17, 3, 'Hanya pembeli akhir', FALSE),
(17, 4, 'Pemerintah', FALSE),

(18, 1, 'Pengelola usaha saja', FALSE),
(18, 2, 'Pihak yang memberikan pembiayaan', TRUE),
(18, 3, 'Penjual barang', FALSE),
(18, 4, 'Penyewa aset', FALSE),

(19, 1, 'Nomor urutan nama', FALSE),
(19, 2, 'Persentase yang disepakati bersama', TRUE),
(19, 3, 'Besar fisik pengelola', FALSE),
(19, 4, 'Lokasi bank', FALSE),

(20, 1, 'Satu pihak memberi uang, pihak lain mengelola usaha, hasil dibagi', TRUE),
(20, 2, 'Satu pihak menjual barang tunai', FALSE),
(20, 3, 'Menyewa ruang kantor seharian', FALSE),
(20, 4, 'Memberikan sukarela tanpa kepastian', FALSE),

(21, 1, 'Musyarakah tidak melibatkan uang', FALSE),
(21, 2, 'Musyarakah melibatkan kontribusi dari beberapa pihak dalam modal dan/atau keahlian', TRUE),
(21, 3, 'Musyarakah hanya untuk sewa', FALSE),
(21, 4, 'Musyarakah tidak perlu akad', FALSE),

(22, 1, 'Nomor antrian', FALSE),
(22, 2, 'Persentase kontribusi atau kesepakatan yang disepakati', TRUE),
(22, 3, 'Yang paling dulu datang', FALSE),
(22, 4, 'Besar badan pengelola', FALSE),

(23, 1, 'Satu orang memberi modal dan orang lain mengelola saja', FALSE),
(23, 2, 'Dua mitra sama-sama memberi modal dan berdiskusi dalam pengelolaan', TRUE),
(23, 3, 'Menyewa ruang kantor sebesar mungkin', FALSE),
(23, 4, 'Menjual barang dengan marjin tersembunyi', FALSE),

(24, 1, 'Tidak punya peran', FALSE),
(24, 2, 'Memberikan kontribusi sesuai kesepakatan', TRUE),
(24, 3, 'Hanya menonton', FALSE),
(24, 4, 'Menjual tanpa partisipasi', FALSE),

(25, 1, 'Hanya satu orang yang ingin mengambil risiko', FALSE),
(25, 2, 'Beberapa pihak ingin berinvestasi bersama', TRUE),
(25, 3, 'Barang dijual tanpa pembicaraan', FALSE),
(25, 4, 'Sewa dilakukan secara diam-diam', FALSE),

(26, 1, 'Menjual barang dengan harga tinggi', FALSE),
(26, 2, 'Menyewakan aset untuk penggunaan dalam waktu tertentu', TRUE),
(26, 3, 'Meminjamkan uang dengan bunga', FALSE),
(26, 4, 'Menyumbang barang tanpa syarat', FALSE),

(27, 1, 'Penyewa selama periode sewa', TRUE),
(27, 2, 'Penjual di seluruh masa', FALSE),
(27, 3, 'Pengelola dana', FALSE),
(27, 4, 'Penjamin kredit', FALSE),

(28, 1, 'Membeli mobil baru secara tunai', FALSE),
(28, 2, 'Menyewa alat kantor untuk proyek tertentu', TRUE),
(28, 3, 'Menyumbang buku ke perpustakaan', FALSE),
(28, 4, 'Menanam pohon di sawah', FALSE),

(29, 1, 'Aset tetap menjadi hak penyewa selama sewa', TRUE),
(29, 2, 'Aset langsung berpindah kepemilikan', FALSE),
(29, 3, 'Barang hilang begitu saja', FALSE),
(29, 4, 'Harga tidak penting', FALSE),

(30, 1, 'Barang tidak dipakai sama sekali', FALSE),
(30, 2, 'Jangka waktu dan ketentuan penggunaan aset', TRUE),
(30, 3, 'Modal yang tidak dikembalikan', FALSE),
(30, 4, 'Sewa tanpa batas waktu tanpa aturan', FALSE),

(31, 1, 'Tidak ada biaya sewa', FALSE),
(31, 2, 'Pada akhirnya bisa mengarah pada kepemilikan aset', TRUE),
(31, 3, 'Hanya berlaku untuk makanan', FALSE),
(31, 4, 'Dilakukan tanpa akad', FALSE),

(32, 1, 'Menyewa rumah untuk liburan singkat', FALSE),
(32, 2, 'Menyewa aset dengan opsi kepemilikan di akhir', TRUE),
(32, 3, 'Menjual sepeda kepada tetangga', FALSE),
(32, 4, 'Meminjam buku dari perpustakaan', FALSE),

(33, 1, 'Sewa otomatis berhenti tanpa klausul', FALSE),
(33, 2, 'Aset bisa beralih kepemilikan sesuai ketentuan yang disepakati', TRUE),
(33, 3, 'Penyewa kehilangan semua hak', FALSE),
(33, 4, 'Penjual wajib merusak aset', FALSE),

(34, 1, 'Penutupan sewa tanpa akhir', FALSE),
(34, 2, 'Kemungkinan kepemilikan di akhir', TRUE),
(34, 3, 'Penyewaan tanpa aturan', FALSE),
(34, 4, 'Kerusakan aset', FALSE),

(35, 1, 'Agar penyewa bisa memakai aset lalu memilikiinya sesuai kesepakatan', TRUE),
(35, 2, 'Agar aset hilang', FALSE),
(35, 3, 'Agar harga tetap sembunyi', FALSE),
(35, 4, 'Agar tidak ada akhir', FALSE),

(36, 1, 'Peminjam dan bank saja', FALSE),
(36, 2, 'Pemberi wewenang dan wakil yang menjalankan tugas tertentu', TRUE),
(36, 3, 'Penyewa dan penyewa lanjutan', FALSE),
(36, 4, 'Penjual dan pembeli tunai', FALSE),

(37, 1, 'Penjamin', FALSE),
(37, 2, 'Wakil', TRUE),
(37, 3, 'Penyewa', FALSE),
(37, 4, 'Pedagang eceran', FALSE),

(38, 1, 'Menyewakan motor untuk satu hari', FALSE),
(38, 2, 'Memberikan wewenang orang lain untuk mengurus urusan tertentu', TRUE),
(38, 3, 'Menjual buku di jalan', FALSE),
(38, 4, 'Meminjam uang dari koperasi', FALSE),

(39, 1, 'Bertindak atas nama pemberi wewenang dalam lingkup tertentu', TRUE),
(39, 2, 'Merusak aset pemberi wewenang', FALSE),
(39, 3, 'Menjual semua barang tanpa izin', FALSE),
(39, 4, 'Mengabaikan perjanjian', FALSE),

(40, 1, 'Wakil bisa bertindak tanpa aturan', FALSE),
(40, 2, 'Tindakan tetap sesuai yang disepakati', TRUE),
(40, 3, 'Semua keputusan hilang', FALSE),
(40, 4, 'Barang jadi milik wakil', FALSE),

(41, 1, 'Menguntungkan pemberi pinjaman dengan bunga', FALSE),
(41, 2, 'Bersifat membantu tanpa keuntungan tambahan', TRUE),
(41, 3, 'Selalu ditjamin emas', FALSE),
(41, 4, 'Hanya untuk bisnis besar', FALSE),

(42, 1, 'Wajib dibagi sebagai bunga', FALSE),
(42, 2, 'Dapat bersifat sukarela atau pengembalian pokok saja', TRUE),
(42, 3, 'Tidak boleh dikembalikan', FALSE),
(42, 4, 'Dihitung otomatis tiap jam', FALSE),

(43, 1, 'Menjual barang dengan margin 50 persen', FALSE),
(43, 2, 'Memberikan pinjaman untuk membantu kebutuhan dengan pengembalian pokok', TRUE),
(43, 3, 'Menyewakan rumah dengan persentase hasil', FALSE),
(43, 4, 'Membeli saham tanpa risiko', FALSE),

(44, 1, 'Keuntungan pihak pemberi', FALSE),
(44, 2, 'Bantuan kepada pihak yang membutuhkan', TRUE),
(44, 3, 'Sewa aset', FALSE),
(44, 4, 'Pembagian modal', FALSE),

(45, 1, 'Tujuannya meminta bantuan bukan mencari untung', TRUE),
(45, 2, 'Tujuannya menjual barang', FALSE),
(45, 3, 'Tujuannya menyewa alat', FALSE),
(45, 4, 'Tujuannya membagi hasil usaha', FALSE),

(46, 1, 'Penjualan barang secara masa depan', FALSE),
(46, 2, 'Pencatutan uang atau aset dengan penekanan pada keamanan', TRUE),
(46, 3, 'Sewa alat industri', FALSE),
(46, 4, 'Pinjaman berbunga', FALSE),

(47, 1, 'Menyembunyikan alasan', FALSE),
(47, 2, 'Menjaga kepercayaan dan perlindungan aset', TRUE),
(47, 3, 'Meningkatkan risiko', FALSE),
(47, 4, 'Mengurangi jumlah aset', FALSE),

(48, 1, 'Menjual hasil panen sebelum panen', FALSE),
(48, 2, 'Menitipkan uang dengan perjanjian keamanan', TRUE),
(48, 3, 'Menyewa truk pengiriman', FALSE),
(48, 4, 'Memberikan bunga kepada nasabah', FALSE),

(49, 1, 'Menyimpan aset dengan perlindungan yang jelas', TRUE),
(49, 2, 'Menjual aset secara langsung', FALSE),
(49, 3, 'Menyewa alat produksi', FALSE),
(49, 4, 'Memberikan bunga', FALSE),

(50, 1, 'Keuntungan tambahan', FALSE),
(50, 2, 'Keamanan aset yang dititipkan', TRUE),
(50, 3, 'Pembagian hasil usaha', FALSE),
(50, 4, 'Sewa jangka panjang', FALSE),

(51, 1, 'Menjual makanan', FALSE),
(51, 2, 'Menjamin pemenuhan kewajiban pihak lain', TRUE),
(51, 3, 'Menyewa alat tulis', FALSE),
(51, 4, 'Menanam pohon', FALSE),

(52, 1, 'Pendaftar investasi', FALSE),
(52, 2, 'Penjamin apabila ada kewajiban yang perlu dipenuhi', TRUE),
(52, 3, 'Penjual barang', FALSE),
(52, 4, 'Pedagang eceran', FALSE),

(53, 1, 'Memberikan jaminan atas kewajiban seorang mitra usaha', TRUE),
(53, 2, 'Menjual sepeda bekas', FALSE),
(53, 3, 'Menyewakan laptop', FALSE),
(53, 4, 'Mengambil pinjaman berbunga', FALSE),

(54, 1, 'Ada kebutuhan jaminan atas kewajiban tertentu', TRUE),
(54, 2, 'Barang dijual tanpa penjelasan', FALSE),
(54, 3, 'Modal tidak punya mitra', FALSE),
(54, 4, 'Sewa tidak perlu perjanjian', FALSE),

(55, 1, 'Kafalah berfokus pada menjamin pemenuhan kewajiban, Rahn memberi jaminan atas aset tertentu', TRUE),
(55, 2, 'Keduanya sama persis', FALSE),
(55, 3, 'Kafalah tidak butuh pihak lain', FALSE),
(55, 4, 'Kafalah hanya untuk makanan', FALSE),

(56, 1, 'Jaminan berupa hak milik tertentu untuk mengamankan kewajiban', TRUE),
(56, 2, 'Sewa tahunan', FALSE),
(56, 3, 'Barang hasil donasi', FALSE),
(56, 4, 'Jenis bunga', FALSE),

(57, 1, 'Tidak berkaitan sama sekali', FALSE),
(57, 2, 'Milik pihak yang memberikan jaminan', TRUE),
(57, 3, 'Harta benda yang hilang', FALSE),
(57, 4, 'Hak suara saja', FALSE),

(58, 1, 'Menyewakan kendaraan', FALSE),
(58, 2, 'Menjamin kewajiban dengan memberikan hak atas aset tertentu', TRUE),
(58, 3, 'Menjual buku pribadi', FALSE),
(58, 4, 'Memberikan barang secara gratis', FALSE),

(59, 1, 'Jaminan tambahan untuk kewajiban', TRUE),
(59, 2, 'Pembagian hasil usaha', FALSE),
(59, 3, 'Sewa alat tahunan', FALSE),
(59, 4, 'Donasi tanpa syarat', FALSE),

(60, 1, 'Aset digunakan sebagai jaminan atas pinjaman atau kewajiban', TRUE),
(60, 2, 'Barang dijual tanpa harga', FALSE),
(60, 3, 'Barang disewakan tanpa syarat', FALSE),
(60, 4, 'Barang diberikan secara sukarela tanpa jaminan', FALSE);

INSERT INTO quiz_jawaban_benar (soal_id, answer_index) VALUES
(1, 2),
(2, 3),
(3, 2),
(4, 1),
(5, 1),
(6, 2),
(7, 2),
(8, 2),
(9, 2),
(10, 1),
(11, 2),
(12, 2),
(13, 2),
(14, 1),
(15, 2),
(16, 2),
(17, 2),
(18, 2),
(19, 2),
(20, 1),
(21, 2),
(22, 2),
(23, 2),
(24, 2),
(25, 2),
(26, 1),
(27, 2),
(28, 2),
(29, 1),
(30, 2),
(31, 2),
(32, 2),
(33, 2),
(34, 2),
(35, 1),
(36, 2),
(37, 2),
(38, 2),
(39, 1),
(40, 2),
(41, 2),
(42, 2),
(43, 2),
(44, 2),
(45, 1),
(46, 2),
(47, 2),
(48, 2),
(49, 1),
(50, 2),
(51, 2),
(52, 2),
(53, 1),
(54, 1),
(55, 1),
(56, 1),
(57, 2),
(58, 2),
(59, 1),
(60, 1);
